---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: src/pages/events
  label: Events
  create: documents
  match: "**/*.md"
  templates:
  - event
- type: directory
  path: src/pages
  label: Content
  create: none
  match: index.md
  templates:
  - home-page
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: 'npm install --legacy-peer-deps '
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
