---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: Site Info
- type: directory
  path: src/pages
  label: Home Page
  create: none
  match: index.md
  templates:
  - home-page
- type: directory
  path: src/pages
  label: About
  create: none
  match: about.md
  templates:
  - about
- type: directory
  path: src/pages
  label: Join
  create: none
  match: join.md
  templates:
  - join-us
- type: heading
  label: Blogs & Events
- type: directory
  path: src/pages/events
  label: Events
  create: documents
  match: "**/*.md"
  templates:
  - event
- type: directory
  path: src/pages/blog
  label: Blog Posts
  create: documents
  match: "**/*.md"
  templates:
  - blog
upload_dir: https://res.cloudinary.com/mysai/image/upload
public_path: https://res.cloudinary.com/mysai/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry:preview
